-- MySQL 初始化脚本（在本地 3306 执行）
CREATE DATABASE IF NOT EXISTS bigA_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'admin'@'localhost' IDENTIFIED BY '123456';
CREATE USER IF NOT EXISTS 'admin'@'127.0.0.1' IDENTIFIED BY '123456';

GRANT ALL PRIVILEGES ON bigA_db.* TO 'admin'@'localhost';
GRANT ALL PRIVILEGES ON bigA_db.* TO 'admin'@'127.0.0.1';
FLUSH PRIVILEGES;
